[tool.ruff]
line-length = 100
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    ".not_for_git",
    "welcome-page",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A"]
ignore = ["E731"]


[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [".venv", ".not_for_git", "welcome-page"]
reportIncompatibleVariableOverride = "none"
reportAttributeAccessIssue = "none"
reportOptionalMemberAccess = "none"
